In [1]:
import sys
sys.path.insert(0, '../Results')
sys.path.insert(0, '../../src')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import os

from python_utils.visualization_utils import create_summary_table, plot_snr_performance

In [ ]:
if not os.path.exists("Figures"):
    os.mkdir("Figures")

# 10 by 5 Mixing Results

In [2]:
df_predictiveBSS = pd.read_pickle(r"../Results/predictive_bss_noisy_nnsparse_10by5_results.pkl")
df_predictiveBSS.tail()

,Model,seed,SINR,SNR,SNRinp,execution_time
55,LDMIBSS,2701,24.805447,"[[28.677724528122997, 24.214355157044363, 27.2...",30.0,29.060661
56,PredictiveDecorrBSS,2801,25.922622,"[[24.78044985456936, 26.22549859608143, 25.962...",30.0,11.030613
57,LDMIBSS,2801,27.813788,"[[24.510273444905334, 29.83906032332658, 26.85...",30.0,29.144793
58,PredictiveDecorrBSS,2901,24.476274,"[[26.186127991925524, 22.547963010206665, 26.2...",30.0,10.855396
59,LDMIBSS,2901,27.821538,"[[24.955275566246314, 28.02053973158337, 32.02...",30.0,29.406140

In [3]:
create_summary_table(df_predictiveBSS)

                               SINR (dB)     mSNR (dB)      Time (s)
Model               SNRinp
LDMIBSS             30.0    26.49 ± 1.57  27.13 ± 1.14  30.18 ± 3.46
PredictiveDecorrBSS 30.0    21.98 ± 5.55  23.61 ± 3.22  12.62 ± 2.86